linters:
    Indentation:
        severity: error
        width: 4

    NestingDepth:
        enabled: true
        max_depth: 5
        ignore_parent_selectors: false

    SelectorDepth:
        enabled: true
        max_depth: 5

    ImportantRule:
        enabled: false

    IdSelector:
        enabled: false

    ColorKeyword:
        enabled: false

    ColorVariable:
        enabled: false

    Comment:
        enabled: false

    DeclarationOrder:
        enabled: false

    DuplicateProperty:
        enabled: false

    EmptyLineBetweenBlocks:
        enabled: false

    FinalNewline:
        enabled: false

    HexLength:
        enabled: false

    ImportPath:
        enabled: false

    LeadingZero:
        enabled: false

    MergeableSelector:
        enabled: false

    NameFormat:
        enabled: false

    PlaceholderInExtend:
        enabled: false

    PropertySortOrder:
        enabled: false

    QualifyingElement:
        enabled: false

    Shorthand:
        enabled: false

    SingleLinePerSelector:
        enabled: false

    SpaceAfterComma:
        enabled: false

    SpaceAfterPropertyColon:
        enabled: false

    SpaceAfterVariableName:
        enabled: false

    SpaceAroundOperator:
        enabled: false

    SpaceBeforeBrace:
        enabled: false

    SpaceBetweenParens:
        enabled: false

    StringQuotes:
        enabled: false

    UnnecessaryParentReference:
        enabled: false

    VendorPrefix:
        enabled: false

    ZeroUnit:
        enabled: false
