language: node_js
node_js:
    '6'
script: npm run-script deploy
env:
  global:
    GH_REF: github.com/cvknage/news.git
    secure: q3BDR9Kln/ZNWHWy4LNh55qVupoJXvY5k7lpt6cCsQmmmKTx3HMX0tl6dosLJSwj9zMg+cJbNEbgEGAVwNFE3WY6x5qnMj95K7nYRMjwl5nfkn2eQj+5Po5+eTKNSRTc08a1N2eGdwV5pdTQQb73JLrp3kdk6AAmPiWVO3JD1OP0OwR9h7btIzUxAHTTLIEWG3qIkIO7yrSyw4gAYAAmaAAt1MC9u/n75HyoY+Mkx34+jQSargutxRyLL9YKR1zqFVQsv+6BjBw36ulHR+Uz0S+r3CHyynvH7b8lohITdC1FYYqSD/8mnzQ0A0p7to8DGpLUtUjQnatNXYHrZelQXtORQnBpwrnPCKtzD9nKNLCFr7vr7YyB+1Uhfo+dG4JczJ7B5REaB65iRkHbxkvtNc9BNt+idIRrkkEPPjdHzXeKtILw6dTOAz+2pv35sdwkEMIr/scrNc0KBJUEoaZH0hSrSBGJV7CTQQTPnzb2sUr6+tLxankSHm1DiGKladelN1msZXG+fGCt2V9nLWmpU9CBPWGjfHltdqen9J+gAdqgA1SlJrUg/t5IEqG6VOcao+xQTsHfPtzGmfXs8839YR2oil6Qffj8o7EBREsrXniElwLQZ76ZetUxwnnhykOv2BMmZp8LuQm/UsgzDFHlxMH03ZBIc3quQbw3MqRC9U4=
before_install:
    gem install scss-lint
